### ISSUE TITLE
Create standalone C++ lib for gzip compression

### ISSUE THREAD

**Issue by springmeyer** [mapbox/cpp#10]
The zlib/gzip compression headers of mapnik-vt, if extracted, would be useful a number of places immediately:
- To immediately start sharing code between mapnik-vt/node-mapnik and tippecanoe (also the shaver and china-cutout)
- To be available to other libraries like https://github.com/mapbox/vector-tile

TODO:
- [ ] New repo called mapbox/gzip-cpp
- [ ] Make able to be used header only, or as a compiled lib (by using `_impl.hpp` design per https://github.com/mapbox/geojson-cpp/pull/24
- [ ] Package in mason
- [ ] Re-integrate back into mapnik-vt as a new dependency
- [ ] Formalize document on how `_impl.hpp` headers work in /cpp docs. - started at https://github.com/mapbox/cpp/issues/12

Sources to pull from include: https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_compression.hpp and https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_compression.ipp. (NOTE: The `ipp` file is == to `_impl.hpp`)

Extras ideas:
- Could leverage https://github.com/madler/zlib/blob/2fa463bacfff79181df1a5270fb67cc679a53e71/uncompr.c

/cc @GretaCB @mapsam

**Comment by mapsam** [comment]
This is moving over at https://github.com/mapbox/gzip-hpp

**Comment by springmeyer** [comment]
👍  thanks @mapsam - will close this now.

**Comment by springmeyer** [comment]
Tracking first release of gzip-hpp at https://github.com/mapbox/gzip-hpp/milestone/1
