### ISSUE TITLE
Move node-cpp-versioning into this repo

### ISSUE THREAD

**Issue by mapsam** [mapbox/cpp#11]
Is it worth moving the node-cpp versioning document into this repo? https://github.com/mapbox/versioning-node-cpp

cc @GretaCB @springmeyer

**Comment by GretaCB** [comment]
Perhaps keep it as its own repo and link to it from the [`node-cpp.md`](https://github.com/mapbox/cpp/pull/9/files) file?

**Comment by springmeyer** [comment]
@mapsam 👍  for moving it here.

**Comment by mapsam** [comment]
@GretaCB definitely want to link to it from the node-cpp.md file! 

I can be convinced either way 👍 👎  - let me know if I'm getting too gung-ho about consolidating docs 😄

**Comment by GretaCB** [comment]
consolidate 👍 👍 👍

**Comment by springmeyer** [comment]
Thanks for getting this done!
