### ISSUE TITLE
Helpful external links to include

### ISSUE THREAD

**Issue by GretaCB** [mapbox/cpp#13]
Add any external/open blog posts or docs you've found helpful re: C++ and Node, that we can include in the README as reference. This will help us avoid "reinventing the wheel" if there are already good docs out there.

cc @mapsam @mikemorris @springmeyer

**Comment by mikemorris** [comment]
Off the top of my head, favorite links include
- http://lldb.llvm.org/lldb-gdb.html
  - Cheat sheet for `lldb` commands and equivalents in `gdb` - very useful as a quick reference for remembering syntax or trying to figure out what commands could be helpful when you're inside the debugger.
- https://blog.risingstack.com/finding-a-memory-leak-in-node-js/
  - Written for Node.js, but tips on inspecting V8 heap dumps are excellent for finding leaks in Node.js/C++ bindings code.
- https://nodejs.org/en/docs/guides/simple-profiling/
  - Instructions on using the built-in profiler tool in Node.js v4.4.0+ to identify performance bottlenecks in JavaScript or C++ code, this can be useful for remote debugging on Linux machines where using Instruments.app is not an option. Does not show breakdowns for individual threads.

**Comment by mapsam** [comment]
[On problems with threads in node.js](https://www.future-processing.pl/blog/on-problems-with-threads-in-node-js/): great runthrough of how to properly use `UV_THREADPOOL_SIZE` in Node with some examples

**Comment by springmeyer** [comment]
https://github.com/thlorenz/v8-perf

**Comment by springmeyer** [comment]
We've got https://github.com/mapbox/cpp/blob/master/node-cpp.md now: let's add to that as needed.
