### ISSUE TITLE
Glossary of C/C++ terms and topics

### ISSUE THREAD

**Issue by springmeyer** [mapbox/cpp#2]
In order to support the documentation goals in #1, we should start developing a glossary of terms and topics.

**Comment by mapsam** [comment]
Instead of build an unordered list, let's make each term _linkable_ with a fragment. 

ie.

```
### posix
### dynamic/shared library
### static library
```

This will allow us to link to the glossary from the README and other docs.

**Comment by springmeyer** [comment]
Progress in #14. Going to close this issue. We can keep on adding and improving as we go.
