### ISSUE TITLE
What is CXX used for?

### ISSUE THREAD

**Issue by mapsam** [mapbox/cpp#24]
What is CXX used for and why do we need it? 

*possibly a glossary term?*

cc @springmeyer @flippmoke @artemp @GretaCB @millzpaugh

**Comment by daniel-j-h** [comment]
https://github.com/mapbox/morec2/pull/126#issuecomment-283612940

**Comment by mapsam** [comment]
From @daniel-j-h! 

> there is a convention on Linux to have the environment variable
> - `CPP` be the C Pre-Processor - the program reading your code and replacing header includes with their content and macros with their values
> - `CC` the C Compiler - the program understanding the C language, taking a .c source code file and generating a .o object file out of it
> - `CXX` the C++ Compiler - the program understanding the C++ language, taking a .cc/.cpp source code file and generating a .o object file out of it
> - `LD` the linker - the program taking multiple .o files and libraries .so/.a (e.g. libboost) and generating an executable ELF file out of it - the final binary
> 
> then for passing in flags
> - `CFLAGS` compilation flags for the C compiler, think `-Wall -Wextra -pedantic -O2 -std=c99` to enable warnings, optimize the code and work with C99 source code
> - `CXXFLAGS` same for C++, `-Wall -Wextra -pedantic -O2 -std=c++14`
> - `LDFLAGS` linker flags, for more advanced linker tuning
> 
> Build systems such as Make, CMake and Gyp (what we use here) pick up these environment variables and use them for compiling and linking your code. If you leave them blank it depends on the build system and your setup what you will get.

**Comment by springmeyer** [comment]
Thanks for creating this ticket @mapsam. I've been working on improving the glossary with @GretaCB last couple days and worked to integrate this. I'll close this ticket now and track at #27 - would appreciate review and copyedits over there.

**Comment by suchi13giri** [comment]
can anyone explain me that in my android phone i create a folder and inside it put one .cxx file (code), but i unable to understand that when i click this file then it redirect me to termux why it is happening?? why it redirect to termux?
