### ISSUE TITLE
Organize content

### ISSUE THREAD

**Issue by mapsam** [mapbox/cpp#42]
This repo has gained an extraordinary amount of content over time and it feels like it's time to add a bit of organization. It's not very clear where the line is drawn between README and separate markdown files. Now that we have a `/docs` directory to use (thanks to https://github.com/mapbox/cpp/pull/34) let's take advantage. I recommend reducing the README significantly and generating a table of contents. Based on the information in the README and the /docs folder, I see two major types of documents here: 

1. General C++, context building pages, setting up your workflow/system pages 
1. Style and research guides (metaprogramming, static types) about writing C++, almost "tutorials" but not quite

### Table of contents

* General C++ @ Mapbox (standard compilers and libraries)
* Installing & packaging C++ (Mason, travis, etc)
* Testing & coverage
* Node.js addons (writing C++ for Node.js modules)
* External learning resources (skeleton libraries, reading, videos)
* Glossary
* FAQ (things that have no home)

### Guides

* [Structural metaprogramming](https://github.com/mapbox/cpp/blob/master/C%2B%2B%20Structural%20Metaprogramming.md)
* [Strong types](https://github.com/mapbox/cpp/blob/master/docs/strong_types.md)
* [Troubleshooting](https://github.com/mapbox/cpp/blob/master/troubleshooting.md) (profiling, debugging)

I'm not tied to the "general setup" vs. "guides" differentiation, perhaps that's overoptimized. Additionally, I think it'd be excellent to add a CONTRIBUTING.md and CODE_OF_CONDUCT.md to provide a comfortable space for others to contribute and participate.

cc @mapbox/core-tech

**Comment by mapsam** [comment]
Additionally, we could clean up the "Where at Mapbox section" but keep it as part of the introduction in the README

> The C++ language and projects built on top of it are essential to the Mapbox platform. This is the place to start for developing and deploying C++ at Mapbox. You'll find information about best-practices, gotchas, and helpful libraries/resources for beginning to develop in C++. Some of the major C++ projects at Mapbox are:
> 
>   - Map rendering with [Mapbox GL Native](https://github.com/mapbox/mapbox-gl-native), the core codebase shared between all of the native frontend SDKs, some of which are also in C++ like [Qt](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/qt/), and the [macOS SDK](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/macos/) or  [iOS](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/), which is in Objective-C++ (a hybrid language).
>   - Mapbox directions is based on [OSRM](https://github.com/Project-OSRM/osrm-backend)
>   - Mapbox geocoding uses [carmen-cache](https://github.com/mapbox/carmen-cache) for indexes
>   - Mapbox tile services use [Mapnik](https://github.com/mapnik/mapnik) and [node-mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/node)
>   - Mapbox scripts for processing OSM are often based on [libosmium](https://github.com/osmcode/libosmium). [Minjur](https://github.com/mapbox/minjur) creates geojson and [tippecanoe](https://github.com/mapbox/tippecanoe) creates vector tiles for [OSM QA tiles](https://osmlab.github.io/osm-qa-tiles/).

**Comment by springmeyer** [comment]
👍  @mapsam to all the ideas above. I'm supportive of making the readme minimal and organizing docs logically.

**Comment by mapsam** [comment]
Organized! ✨
