### ISSUE TITLE
Make and Cmake basics

### ISSUE THREAD

**Issue by springmeyer** [mapbox/cpp#5]
Make and Cmake are in common usage at Mapbox.
- Make for very small standalone projects
- Cmake for larger projects and shared libraries

We should document successful patterns for each, best practices, and gochas
- @BergWerkGIS - can you draft up docs on cmake based on your recent work?
- @ericfischer - interested in taking a pass at Makefile docs?

Topics to cover:
- How to install recent cmake via mason
- How to integrate mason deps into cmake and make projects

/cc @mapsam @GretaCB

**Comment by springmeyer** [comment]
refs https://github.com/mapbox/cpp-bootstrap from @kkaefer

**Comment by e-n-f** [comment]
Sure @springmeyer, I can write something. Working on it in https://gist.github.com/ericfischer/3195e7c06ef0f55b73623b9f6526544d

**Comment by springmeyer** [comment]
Awesome thank you @ericfischer 🙏

**Comment by mikemorris** [comment]
Would be great if we could include the `node-cmake` build system @kkaefer [rigged up in mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/blob/master/cmake/node.cmake) either in this doc or over in https://github.com/mapbox/node-cpp-skel

**Comment by springmeyer** [comment]
noting: osrm-backend now has pioneered a clean way to use mason deps in a cmake project while still allowing developers to build against custom version of deps if they choose. This is done via an option: https://github.com/Project-OSRM/osrm-backend/blob/master/CMakeLists.txt#L17. I think this should be considered best practice for even small projects whereby:

 - ENABLE_MASON=ON is the default
 - But you can disable mason deps and fallback to cmake using `find_package` to find things.

This would enable all projects to self-document their versions and work seamlessly on osx and linux while keeping the option open of someone porting to a new system like windows.

**Comment by springmeyer** [comment]
Closing, https://github.com/mapbox/hpp-skel now has examples of using mason + cmake. And I've moved @ericfischer's `make` docs into `./docs` in 443b23f
